language: go

go:
  - 1.x
  - "1.10"
  - 1.11.x
  - tip

os:
  - linux
  - osx

script:
  - go test -race -coverprofile=cover.out -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
